/**
 * MiTruCo Exam Triage Card Component
 * Specialized 80/20 High-Yield Strategy & Stress Triage for competitive exams:
 * Civil Services (UPSC), Medical (NEET/MBBS), Law (CLAT/Judiciary), Architecture (NATA), and Pre-Boards.
 */

import React, { useState } from 'react';
import {
  GraduationCap,
  Landmark,
  Stethoscope,
  Scale,
  Building2,
  FileCheck,
  CheckCircle2,
  XCircle,
  Clock,
  AlertTriangle,
  Copy,
  Check,
  Download,
  ShieldAlert,
  Flame,
} from 'lucide-react';
import { ExamTriageCardData } from '../../types';
import { useApp } from '../../context/AppContext';

interface ExamTriageCardProps {
  data: ExamTriageCardData;
}

export const ExamTriageCard: React.FC<ExamTriageCardProps> = ({ data }) => {
  const { themeConfig, addDownloadFile } = useApp();
  const [copiedKeyword, setCopiedKeyword] = useState<string | null>(null);

  const getExamIcon = () => {
    switch (data.examCategory) {
      case 'civil_services':
        return <Landmark className="w-5 h-5 text-indigo-500" />;
      case 'mbbs_neet':
        return <Stethoscope className="w-5 h-5 text-emerald-500" />;
      case 'law_clat':
        return <Scale className="w-5 h-5 text-purple-500" />;
      case 'architecture_nata':
        return <Building2 className="w-5 h-5 text-amber-500" />;
      case 'pre_board':
        return <FileCheck className="w-5 h-5 text-blue-500" />;
      default:
        return <GraduationCap className="w-5 h-5 text-blue-500" />;
    }
  };

  const handleCopyKeyword = (kw: string) => {
    navigator.clipboard.writeText(kw);
    setCopiedKeyword(kw);
    setTimeout(() => setCopiedKeyword(null), 2000);
  };

  const handleExportRevisionSheet = async () => {
    const text = `# ${data.title} — 80/20 High-Yield Triage\n` +
      `Target Exam: ${data.targetExam}\n` +
      `Stress Assessment: ${data.stressLevel.toUpperCase()}\n` +
      `Syllabus Source: ${data.verifiedSyllabusWeightage || 'Standard Authority'}\n\n` +
      `## 1. MUST-MASTER 80/20 HIGH-YIELD TOPICS:\n` +
      data.triage80_20.mustDo.map((item, idx) => `[MUST ${idx + 1}] ${item}`).join('\n') +
      `\n\n## 2. SAFE TO DE-PRIORITIZE IF PANICKING / SHORT ON TIME:\n` +
      data.triage80_20.canSkipIfUnderPressure.map((item, idx) => `[SKIP ${idx + 1}] ${item}`).join('\n') +
      `\n\n## 3. RAPID FORMULAS & KEYWORDS:\n` +
      data.rapidFormulasOrKeywords.join(' · ') +
      `\n\n## 4. TIME-ATTACK STRATEGY:\n${data.timeAttackStrategy}\n\n` +
      `## 5. PITFALLS TO AVOID:\n` +
      data.pitfallsToAvoid.map((item, idx) => `- [!] ${item}`).join('\n') +
      `\n\n## Reassurance:\n${data.reassuranceSnippet}\n\n` +
      `Generated by MiTruCo — Made with care from Bihar — GR_`;

    await addDownloadFile(`${data.targetExam.replace(/[^a-zA-Z0-9]/g, '_')}_triage_sheet.txt`, text, 'text/plain');
    alert('High-yield revision sheet exported to Downloads!');
  };

  return (
    <div
      id={`exam_triage_${data.id}`}
      className="p-5 rounded-2xl border shadow-sm space-y-4 my-2"
      style={{
        backgroundColor: themeConfig.surfaceBase,
        borderColor: themeConfig.borderBase,
        color: themeConfig.textBase,
      }}
    >
      {/* Header */}
      <div className="flex items-start justify-between gap-3 border-b pb-3" style={{ borderColor: themeConfig.borderBase }}>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl flex items-center justify-center bg-black/5 dark:bg-white/5 shrink-0 border" style={{ borderColor: themeConfig.borderBase }}>
            {getExamIcon()}
          </div>
          <div>
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs font-bold uppercase tracking-wider opacity-75">
                {data.targetExam}
              </span>
              <span
                className={`px-2 py-0.5 rounded-full text-[10px] font-bold uppercase flex items-center gap-1 ${
                  data.stressLevel === 'critical'
                    ? 'bg-red-500/15 text-red-600 dark:text-red-400 border border-red-500/30'
                    : 'bg-amber-500/15 text-amber-600 dark:text-amber-400 border border-amber-500/30'
                }`}
              >
                <Flame className="w-3 h-3" />
                <span>{data.stressLevel === 'critical' ? 'High-Yield Recovery' : 'Tactical Triage'}</span>
              </span>
            </div>
            <h3 className="text-base font-bold tracking-tight mt-0.5">{data.title}</h3>
          </div>
        </div>

        <button
          id={`btn_export_triage_${data.id}`}
          onClick={handleExportRevisionSheet}
          className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs font-semibold hover:opacity-85 transition-opacity shrink-0"
          style={{
            borderColor: themeConfig.borderBase,
            backgroundColor: themeConfig.bgBase,
            color: themeConfig.textBase,
          }}
          title="Export high-yield revision sheet"
        >
          <Download className="w-3.5 h-3.5" />
          <span className="hidden sm:inline">Export Sheet</span>
        </button>
      </div>

      {/* 80/20 Triage Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs">
        {/* Must-Do High-Yield (80% score weight) */}
        <div className="p-3.5 rounded-xl border border-emerald-500/30 bg-emerald-500/5 space-y-2">
          <div className="flex items-center gap-1.5 font-bold text-emerald-700 dark:text-emerald-300">
            <CheckCircle2 className="w-4 h-4 text-emerald-600" />
            <span>High-Yield Must-Master (Top 20% effort → 80% marks):</span>
          </div>
          <ul className="space-y-1.5 pl-1">
            {data.triage80_20.mustDo.map((item, idx) => (
              <li key={idx} className="flex items-start gap-1.5 leading-relaxed text-stone-800 dark:text-stone-200">
                <span className="font-bold text-emerald-600 dark:text-emerald-400 shrink-0">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Safe to De-Prioritize */}
        <div className="p-3.5 rounded-xl border border-stone-300 dark:border-stone-700 bg-stone-500/5 space-y-2">
          <div className="flex items-center gap-1.5 font-bold text-stone-600 dark:text-stone-400">
            <XCircle className="w-4 h-4 opacity-75" />
            <span>Safe to De-Prioritize if Panicking / Low Time:</span>
          </div>
          <ul className="space-y-1.5 pl-1">
            {data.triage80_20.canSkipIfUnderPressure.map((item, idx) => (
              <li key={idx} className="flex items-start gap-1.5 leading-relaxed opacity-75 text-stone-600 dark:text-stone-400">
                <span className="font-bold shrink-0">✕</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Rapid Formulas / Landmark Keywords Chips */}
      {data.rapidFormulasOrKeywords && data.rapidFormulasOrKeywords.length > 0 && (
        <div className="space-y-1.5 text-xs">
          <div className="font-bold opacity-80">Rapid Recall Formulas & Keywords:</div>
          <div className="flex flex-wrap gap-1.5">
            {data.rapidFormulasOrKeywords.map((kw, idx) => (
              <button
                key={idx}
                onClick={() => handleCopyKeyword(kw)}
                className="flex items-center gap-1 px-2.5 py-1 rounded-lg border text-[11px] font-mono hover:opacity-80 transition-all active:scale-95"
                style={{
                  borderColor: themeConfig.borderBase,
                  backgroundColor: themeConfig.bgBase,
                  color: themeConfig.textBase,
                }}
                title="Click to copy"
              >
                <span>{kw}</span>
                {copiedKeyword === kw ? (
                  <Check className="w-3 h-3 text-emerald-500 shrink-0" />
                ) : (
                  <Copy className="w-3 h-3 opacity-50 shrink-0" />
                )}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Time-Attack Strategy */}
      <div className="p-3 rounded-xl border text-xs flex items-start gap-2.5" style={{ borderColor: themeConfig.borderBase, backgroundColor: themeConfig.bgBase }}>
        <Clock className="w-4 h-4 text-blue-500 shrink-0 mt-0.5" />
        <div className="space-y-0.5">
          <span className="font-bold">Time-Attack Strategy:</span>
          <p className="opacity-90 leading-relaxed">{data.timeAttackStrategy}</p>
        </div>
      </div>

      {/* Pitfalls & Traps to Avoid */}
      {data.pitfallsToAvoid && data.pitfallsToAvoid.length > 0 && (
        <div className="p-3 rounded-xl border border-red-500/20 bg-red-500/5 text-xs space-y-1.5">
          <div className="flex items-center gap-1.5 font-bold text-red-600 dark:text-red-400">
            <AlertTriangle className="w-4 h-4 shrink-0" />
            <span>Avoid These Costly Exam Pitfalls:</span>
          </div>
          <ul className="space-y-1 pl-1 text-stone-700 dark:text-stone-300">
            {data.pitfallsToAvoid.map((pit, idx) => (
              <li key={idx} className="flex items-start gap-1.5">
                <span className="text-red-500 font-bold shrink-0">!</span>
                <span>{pit}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Reassurance & Syllabus Authority */}
      <div className="flex items-center justify-between gap-2 pt-2 border-t text-[11px] opacity-75" style={{ borderColor: themeConfig.borderBase }}>
        <span className="italic">"{data.reassuranceSnippet}"</span>
        {data.verifiedSyllabusWeightage && (
          <span className="shrink-0 font-medium font-mono text-[10px] px-2 py-0.5 rounded-md border" style={{ borderColor: themeConfig.borderBase }}>
            {data.verifiedSyllabusWeightage}
          </span>
        )}
      </div>
    </div>
  );
};
